### ISSUE TITLE
Parsing is broken since color update

### ISSUE THREAD

**Issue by nickmoeck** [jonnyynnoj/haxball-replay-parser#1]
The update that allows you to set the colors of each team's hax-dots has caused the replay parser to break completely.  It would be nice to see this fixed.

**Comment by jonnyynnoj** [comment]
Unfortunately the method I use to view the haxball source code has stopped working since the loading bar feature was implemented so I can't see how the colours are implemented. I'll try get hold of basro and see if he can shed some light on this.

**Comment by saviola777** [comment]
I guess this is a needless question, but: any updates on this? How realistic is it to try to identify and ignore the commands within the replay file which correspond to setting custom colors without having access to the original source code?

**Comment by jonnyynnoj** [comment]
Well it should be possible. I did initially try skipping any color information but couldn't figure out a consistent structure that would indicate how many bytes to skip. I doubt I'll take another look at it, but if you want to it should be possible through some trial and error.

**Comment by saviola777** [comment]
I see, thanks for your response. Will see what I can do, but I have no previous experience working with binary data... Guess I'll learn something new!

**Comment by jonnyynnoj** [comment]
Fixed in 9c1944a1998c0ec60fcae98e3c27cfd6800a8bea
