### ISSUE TITLE
Action type 20 invalid

### ISSUE THREAD

**Issue by 3min** [jonnyynnoj/haxball-replay-parser#2]
Uncaught exception 'InvalidArgumentException' with message 'Action type 20 invalid' in /usr/share/nginx/fm-haxball/shared/vendor/jonnyynnoj/haxball-replay-parser/src/Parser.php:154
[2017-03-22-replay.hbr.zip](https://github.com/jonnyynnoj/haxball-replay-parser/files/861463/2017-03-22-replay.hbr.zip)

Is it possible to fix this problem?

**Comment by jonnyynnoj** [comment]
Thanks for reporting this, should be fixed now 👍
